spring:
  h2.console:
    enabled: true
    path: '/h2'
    url: 'jdbc:h2:mem:accountsdb'
    username: 'sa'
    password: ${H2_PASSWORD}
    driver-class-name: 'org.h2.Driver'
  jpa:
    database-platform: 'org.hibernate.dialect.H2Dialect'

security.require-ssl: true
server:
  port: 8445
  ssl.key-store-type: 'JKS'
  ssl.key-store: ${CLIENT_KEYSTORE_PATH}
  ssl.key-store-password: ${CLIENT_KEYSTORE_PASSWORD}
  ssl.key-alias: 'client'

keystore:
  client:
    password: ${JWT_KEYSTORE_PASSWORD}
    path: ${JWT_KEYSTORE_PATH}
---
spring:
  profiles: local
  datasource:
    password:

keystore:
  client:
    password: 'changeit'
    path: 'implementation/src/main/resources/jwt-keystore.p12'

server:
  ssl.key-store: 'client.jks'
  ssl.key-store-password: 'changeit'